/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` or `next build`.
// It's checked in here so the project type-checks before the first build.
